In [6]:
import numpy as np

x1 = -4
x2 = -6
minomax = 0
res = 2
mres = np.array([[-1,1,11],[1,1,27]])
 

In [7]:
def difs(res,a,x):

    dif = np.zeros((res))
    
    for i in range(res):
        dif[i] = a[i+1,res+2]/a[i+1,x]
        print(dif[i])

    for i in range(res-1):
        if(dif[i]>0 and dif[i] <= dif[i+1]):
            return i
        if(i == res-1):
            return i+1

In [8]:
def graficar(rx):    
    fig = plt.figure(figsize=(6,5))
    left, bottom, width, height = 0.1, 0.1, 0.8, 0.8
    ax = fig.add_axes([left, bottom, width, height])
    
    start, stop, n_values = 0, 30,2000

    x_vals = np.linspace(start, stop, n_values)
    y_vals = np.linspace(start, stop, n_values)
    x1_vals = np.linspace(start, stop, n_values)
    X, Y = np.meshgrid(x_vals, y_vals)
    Z = rx[0,0] * X + rx[0,1] * Y

    # Grafica
    plt.title('Curva de nivel + Restricciones')
    color = ['GreenYellow', 'Olive', 'royalBlue']
    for i in range(res):
        plt.plot(x_vals, (rx[i+1,2]-rx[i+1,0] * x1_vals)/rx[i+1,1], color[i], label=f'R{i+1}')

    # Etiquetas
    plt.legend(bbox_to_anchor=(1.4, 1), loc=0, borderaxespad=0.)

    cp = plt.contourf(X, Y, Z, cmap='Blues')
    plt.colorbar(cp)

    # Guardar graficos
    plt.savefig("graficos.png")
    plt.show()

In [9]:
def simple(x1,x2,minomax,res,mres):

    a = np.zeros((res+1,res+3))
    
    a[0,0] = x1
    a[0,1] = x2
    
    rx = np.zeros((res+1,3))
    
    print(a)
    
    for i in range(res):
        a[i+1,0] = mres[i,0]
        a[i+1,1] = mres[i,1]
        a[i+1,i+2] = 1
        a[i+1,res+2] = mres[i,2]
        
    for i in range(res+1):
        for k in range(2):
            rx[i,k] = a[i,k]
        rx[i,2] = a[i,res+2]
        
    print(a)
    iteration=0
    while(1):
        
        dif = difs(res,a,iteration)
        
        if(iteration >= 2):
            for i in range(res+2):
                if a[0,i]<0:
                    iteration = i
                    break
            for i in range(res):
                if(a[i+1,0]!=1)and(a[i+1,0]!=1):
                    dif=i           
        print(iteration)
        a[dif]= np.divide(a[dif],a[dif,iteration])
        print(dif,iteration)
        if  a[dif,iteration]<0:
            a[dif] = a[dif]*-1
            
        for i in range(res+1):
            print(a)
            if dif!=i:
                a[i] = np.add(a[i],-(a[dif]*a[i,iteration]))
                    
        if iteration < 2:
            iteration = iteration+1
        
        
        if(a[0,0]>=0)and(a[0,1]>=0)and(a[0,2]>=0)and(a[0,3]>=0)and(a[0,4]>=0):
            return a[0,5]

print(simple(x1,x2,minomax,res,mres))  
graficar(rx)

[[-4. -6.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[-4. -6.  0.  0.  0.]
 [-1.  1.  1.  0. 11.]
 [ 1.  1.  0.  1. 27.]]
-11.0
27.0
0
None 0


/var/folders/dm/7czbns1s6j9d9kzxywssklhc0000gn/T/ipykernel_3742/1000001700.py:38: RuntimeWarning: divide by zero encountered in divide
  a[dif]= np.divide(a[dif],a[dif,iteration])
/var/folders/dm/7czbns1s6j9d9kzxywssklhc0000gn/T/ipykernel_3742/1000001700.py:38: RuntimeWarning: invalid value encountered in divide
  a[dif]= np.divide(a[dif],a[dif,iteration])


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()